language: ruby
rvm:
- 2.3.1
script:
- bundle exec rake db:migrate --trace
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec -fd spec/
env:
  secure: "JVlE2KB4CjeMUF3Kqutb7osmVB27gM8B2hulTE5bwdSxbKAVyFqEh/KSXt4MpeHuEdI/PBlQyNUYgrSaxzw+dPTpkfXvNCgaGz2QTnaWr1v9oN0KuaBCzFEoi7okMt8r9GGDT0nfzBczXW09pKpQfj3EDCEWF8juTLFnhN8mg3+0wT0rDBOQWmJSFFWm9zls4uaJDETzDlm8qUePDCQt9z7N+O76spqvKQCPCwu2DwLUc05U7NcVVt7yhs/R5RJUby2ngnxWPcu7/a9dsYItjMCPfjXucst612fxibWByMCHfTujzoQK7t2Rz4wcntWbMac9kqlZCZFvC5EE7HoqF/+RbXWqcHi/hw690AYQJ0m5tMly+9Y5jRykBdU86a24fdWiOEg5cGbWKM6myOSAS/PWGWVegJ/DFs8Y60VRpPqg9onBi+aZ+VgXvwWoiofUSuIsEpcOx/VPcDHc0N8zKWL6yYCd8sQC0xOuhuAglZ4lsY+JC2pqJH6BQc9AbrZCiYojTv5lPMWtHHS4PPDUdJt7W5peC6mmhC+rkoxT5o7iOB+0KwRPd6uM9KqsQMFWPht0tWLYI//SBLarTAcckoR8NNa3LG7Ki+f0KH2y0Dhz4UiYnm3luq8w8PzewkDXWeoAPfxg+jnYMa+WmnCrKh/mZtB22S6hjIc8MykHbLY="
deploy:
  provider: heroku
  api_key:
    secure: s25ewJZHw3HKPYMtQcmZxDzTa+bTd9k9b9vYZRVnPnTLYMTOmD8iqvPJxnZIUhW76Lult59H1j7J1fQF0+96sTX49jV3UomjK6B/sEFDLc0mXXoMP3LYiSMAV6Fkuff7rPJrl8jHvNA0xic7bDm5UDjn7vOQIakFPS8O74SQsB0oxcrvzCH2AIxKUtrfhGaLbKir7Y8HogXVhy1lvjddXhnBOT8GuYbYc/pqDk9tUzoxdqHSBqFZp5HmYGtu6Y2wfaIWf/Nm5SlDwpZkPBIHbLycNuvJt7MfVKxMxFst6cNeNRIadVGpGvl5P5RDL2bI2160nmL9SR2GeXz6GVJU4AJb7dSrl/zxzHQoxLeTdSk++PpnonJdGEB7Dl1aui2JuJu9/EEyCK6mYhjBtrKu4VIIEK61tZ9/cgtSYk47bX5WCHtXoS6uuhB6cIIMeeNA57iAFSzrQ8xGj4X1TNeeYY4r2sZ1S+ZR7asU5qmU2+Jgda275aILJ1x22UzqYAE6QBTKeuWOB6W3NwmcSpt/pVPIRFC5XJ6QzZcBoCwzcQ/L4qWcBs9J3G2/wGiyWIN5Inhk24dzyyfO2Uz+y4JFQOVLji+MHaWnh0xAAqwEd+h96QBjz9t1sZ0EkNx3N4e3MS85d5noevnZhJNf14Eo/ohuhC42vvPK7/LhsRV/BqY=
  app: shielded-journey-53270
#  provider: beermapping
#  api_key:
#    secure:
