# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0363505c5c078718a807e75239b274f222bdfa5d5590fed34fe2f17e6639ab86160f2f1aaf10c62aa4253775003ddc5a2a04d7be0f5bdff51885f247642055b

test:
  secret_key_base: 24753fb28f0cd72cd9cf2338c4dc085d037354eb1c4d8e86b9e9a9df90e3d98a7ccdf08d4d45287e91db47c6994d7b1b3834dcd0fd465f4e333495e12a980b1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
